[package]

name = "test"
version = "0.1.0"
authors = ["Dennis"]

[dependencies]
rustc-serialize = "0.3"

[dependencies.iron]
version = "*"

[dependencies.router]
git = "https://github.com/iron/router.git"
